### Reshaping Arrays

Reshaping an array basically allows us to rearrange the elements of an array - it is still the same elements, but arranged in a new shape.

In [1]:
import numpy as np

In [2]:
arr = np.arange(12)

In [3]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [4]:
arr.shape

(12,)

We can reshape these twelve elements into a 4 x 3 array:

In [5]:
m1 = arr.reshape(4, 3)
m1

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

or into a 2 x 6 array:

In [6]:
m2 = arr.reshape(2, 6)
m2

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11]])

**CAUTION** Reshaping does not modify the original array, however the "positions" in both arrays are shared references.

This means that modifying the element value in one array will affect the element value in the other array.

We'll come back to how we modify array elements, but we can do it using simple indexing, just like we have with lists:

In [7]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [8]:
m1

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

Let's modify the first value of `arr`:

In [9]:
arr[0] = 100

In [10]:
arr

array([100,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11])

As we can see, `arr` was mutated, but observe what happened to `m1` and `m2`:

In [11]:
m1

array([[100,   1,   2],
       [  3,   4,   5],
       [  6,   7,   8],
       [  9,  10,  11]])

In [12]:
m2

array([[100,   1,   2,   3,   4,   5],
       [  6,   7,   8,   9,  10,  11]])

And the same thing happens if we modify an element of either `m1` and `m2`:

In [13]:
m1[3][2] = 200

In [14]:
m1

array([[100,   1,   2],
       [  3,   4,   5],
       [  6,   7,   8],
       [  9,  10, 200]])

In [15]:
m2

array([[100,   1,   2,   3,   4,   5],
       [  6,   7,   8,   9,  10, 200]])

In [16]:
arr

array([100,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10, 200])

So, you should think of reshaping as a different "view" or "rearrangement" of the original array, not an entirely independent copy of the original.

Later we'll see that even NumPyu slices behave the same way, which is very different from Python list slices which return sliced shallow copies.

If we want an independent copy, we can simply make a copy using the `copy` method:

In [17]:
m3 = arr.reshape(3, 4).copy()

In [18]:
m3

array([[100,   1,   2,   3],
       [  4,   5,   6,   7],
       [  8,   9,  10, 200]])

In [19]:
arr

array([100,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10, 200])

In [20]:
arr[1] = -100

In [21]:
arr

array([ 100, -100,    2,    3,    4,    5,    6,    7,    8,    9,   10,
        200])

In [22]:
m3

array([[100,   1,   2,   3],
       [  4,   5,   6,   7],
       [  8,   9,  10, 200]])

As you can see, `m3` was unaffected.

We can also reshape a 2-D array into a 1-D array using the same `reshape` method:

In [23]:
m = np.array(
    [
        [1, 2, 3],
        [4, 5, 6]
    ]
)

In [24]:
m.shape

(2, 3)

In [25]:
arr2 = m.reshape(6)

In [26]:
arr2

array([1, 2, 3, 4, 5, 6])

And of course, the same reference sharing happens:

In [27]:
arr2[2] = 300
arr2

array([  1,   2, 300,   4,   5,   6])

In [28]:
m

array([[  1,   2, 300],
       [  4,   5,   6]])